name: external_library
description: external_library
version: 0.0.1
dependencies:
  angular2: ^2.2.0
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  browser: ^0.10.0  
transformers:
- dart_to_js_script_rewriter
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart